package org.example.rpcprotocol;

public enum RequestType {
    LOGIN,GET_EMPLOYEES,DELETE_EMPLOYEE,ADD_EMPLOYEE,CHANGE_PASSWORD,DEACTIVATE_ACCOUNT,LOGOUT, ADD_BUG, FIND_TESTER,
    GET_BUGS,MODIFY_BUG,SOLVE_BUG, FIND_DEVELOPER, GET_UNFIXED_BUGS, UPDATE
}